### ISSUE TITLE
It crashes when uploading...

### ISSUE THREAD

**Issue by jmescribano** [mikesname/TeiEditions#1]
... giving the following message: 

Warning: require_once(/home/test/plugins/TeiEditions/helpers/../vendor/autoload.php): failed to open stream: No such file or directory in /home/test/plugins/TeiEditions/helpers/TeiEditionsViewHelpers.php on line 9

Fatal error: require_once(): Failed opening required '/home/test/plugins/TeiEditions/helpers/../vendor/autoload.php' (include_path='/home/test/application/libraries:/home/test/application/models:.:/opt/alt/php70/usr/share/pear') in /home/test/plugins/TeiEditions/helpers/TeiEditionsViewHelpers.php on line 9

Thanks in advance.

**Comment by mikesname** [comment]
Thanks for the bug report. This plugin really needs some more documentation or a proper release process. I think the issue you're seeing is dependencies being missing, for which you need to run:

```
composer update
```
in the plugin directory. See the [docs](https://getcomposer.org) for installing the composer tool.

**Comment by jmescribano** [comment]
Yes, that's is. Thanks for replying.
